### ISSUE TITLE
Angular http request is not working with cordova ios

### ISSUE THREAD

**Issue by dhananjaykumar880** [Neos21/angular-cordova#1]
Angular http request is not working with cordova ios 
NSURLConnection finished with error - code -1100

I have changed base href to "." but still not working.

**Comment by Neos21** [comment]
You want to access a local file?
If yes, I recommend using cordova-file plugin instead of.

https://stackoverflow.com/a/46428899

**Comment by khelsisura** [comment]
Does any of you solved the problem? i have a same issue right now
